### ISSUE TITLE
2.6, 2.7 섹션이 아웃라인에 나타나지 않습니다.

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#11]
2.6, 2.7 섹션이 아웃라인에 나타나지 않습니다. 2.5 안으로 폴딩되어 버립니다.  다른 3단계 제목들도 이렇게 되는 경우가 보입니다.

**Comment by docuhut** [comment]
2.6 2.7 섹션은 수정되었습니다. 다른 섹션은 확인해보도록 하겠습니다.
