### ISSUE TITLE
제목 2단계와 3단계가 동일하여 혼란스럽습니다.

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#2]
제목 2단계와 3단계가 동일하여 혼란스럽습니다. 구별되었으면 좋겠습니다. 예를 들어, 3단계 제목이 더 작고 들여쓰기가 되었으면 좋겠습니다.

**Comment by induy** [comment]
현재 사용하고 있는 라이브러리가 제공하는 기능상 제목 2단계와 3단계의 구분이 없습니다. 아쉽게도 별도의 스타일을 제공할수 있는 방안이 없어서 다른 대안을 찾고 있습니다. 이는 시간이 소요될것 같습니다.
대신 제목간에 정렬을 맞추었습니다.
현재 1.2.1 제목과 1.2.2 들은 기능적으로 한개씩만 열려지도록 설계되어 있습니다. 참고하시어 수업에 도움이 되기 바랍니다.

**Comment by docuhut** [comment]
현재 사용하고 있는 라이브러리가 제공하는 기능상 제목 2단계와 3단계의 구분이 없습니다. 아쉽게도 별도의 스타일을 제공할수 있는 방안이 없어서 다른 대안을 찾고 있습니다. 이는 시간이 소요될것 같습니다.
대신 제목간에 정렬을 맞추었습니다.
현재 1.2.1 제목과 1.2.2 들은 기능적으로 한개씩만 열려지도록 설계되어 있습니다. 참고하시어 수업에 도움이 되기 바랍니다.

**Comment by youhj** [comment]
현재 상태는 좀 사용이 곤란한 것 같습니다. 게다가 3단계 제목이 한 개씩만 열리는 기능은 오작동합니다. 예를들어, 3.2.1을 연 후에 아래로 스크롤해서 3.2.2를 오픈하면 화면이 휘리릭하고 엉뚱한 곳으로 스크롤되어 버립니다.

**Comment by docuhut** [comment]
엉뚱하게 스크롤 되는 기능은 이웃 단계를 닫는 기능이 작동되어 오작동되는 것처럼 보이는 것입니다. 
이 닫는 기능을 제거하여 오작동되지 않게 수정하였습니다.
확인하시고 추가 요청사항 있으면 연락 주시기 바랍니다.

**Comment by youhj** [comment]
아직 오작동합니다. 3.2를 연 후에 아래쪽으로 스크롤하여 3.2.1를 열어보십시오.

**Comment by docuhut** [comment]
수정하였습니다.
