### ISSUE TITLE
4.1절의 한 단락 글꼴 스타일 오류

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#20]
4.1절 다음 내용이 들어있는 단락의 글꼴이 이상합니다.

> CSS3 스타일은 선택자(selector)와 선언블록(declaration block)으로 구성된다. 선언블록은 중괄호 ‘{’ 로 시작하여 ‘}’로 끝나며 선언블록 내에는 여러 개의 속성:값 (property : value)이 세미콜론 ; 으로 구분하며 있을 수 있다. 마지막 세미콜론은 생략할 수 있다. EX040102.htm의 p 스타일에 대한 선택자와 속성:값을 구분하면 다음과 같다.

**Comment by docuhut** [comment]
수정되었습니다.
