### ISSUE TITLE
종이 버전에서는 제대로 되어 있으나 온라인 버전에서 누락되거나 형식이 잘못된 문제

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#21]
종이 버전에서는 제대로 되어 있으나 온라인 버전에서 누락되거나 형식이 잘못된 문제가 있습니다. 다음의 예를 발견하였는데 이러한 경우가 또 있을 가능성이 있다고 생각됩니다. 

4.1.2 나. id 선택자 절에서 다음 단락의 앞부분 파일명이 누락되어 있습니다.

> htm의 HTML 문서에서 `<p>` 태그에 대한 스타일을 id=”paragraph1″ 를 이용한 스타일로 바꾸면 EX040104.htm과 같다.

종이 버전에는 다음과 같이 정상적으로 되어 있습니다.

> EX040102.htm의 HTML 문서에서 `<p>` 태그에 대한 스타일을 id="paragraph1" 를
이용한 스타일로 바꾸면 EX040104.htm과 같다.

또 바로 이어지는 내용이 종이 버전에는 다음과  같이 제대로 되어 있는데
```
#paragraph1 {
  color : red;
  font-size : 20px;
}
```
온라인 버전에서는 다음과 같이 잘못 되어 있습니다.

![Screen Shot 2019-04-10 at 15 56 23](https://user-images.githubusercontent.com/10397322/55857858-3c40ef80-5ba9-11e9-9629-4eef36dc289c.png)

**Comment by docuhut** [comment]
수정되었습니다.

**Comment by youhj** [comment]
코드 조각 바로 아래에도 htm으로 시작하는데 파일명이 빠졌습니다. 이런 것이 여기 하나가 아닐 것으로 예상됩니다. 종이 버전과 온라인 버전을 통일해야 합니다. 지금 이상할 때마다 종이 버전을 비교해보고 있는데 이렇게 수작업으로 비교하는 것은 적절하지 않은 작업인 것 같습니다.
