### ISSUE TITLE
4.3절에서 <그림3.1>이 아니라 <그림4.3.1>입니다.

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#24]
4.3절의 다음 부분에서 <그림3.1>이 아니라 <그림4.3.1>입니다. 역시 종이 버전에는 제대로 되어있습니다.

이러한 태그의 한 박스는 <그림3.1>과 같이 다시 4개의 부분집합 사각형 영역, 즉 태그의 문자열이 위치하는 콘텐츠(content), 내부여백 패딩(padding), 테두리(border) 영역, 그리고 외부여백 마진(margin)으로 구성된다.

**Comment by docuhut** [comment]
수정되었습니다.
