### ISSUE TITLE
현재 연습문제의 형식이 의미가 전혀 없습니다. 

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#27]
현재 연습문제의 형식이 의미가 전혀 없습니다. 자동 퀴즈 형식을 필요로 하는 문제가 압니다. 사이드 메뉴에서도 빼고 맨 아래로 옮겨 주십시오.

**Comment by docuhut** [comment]
수정되었습니다.

**Comment by youhj** [comment]
현재 연습문제는 답을 폼에 입력하도록 되어 있는데 그런 형식이 필요한 문제가 없습니다. 그런 형식이 지금 연습문제에 맞지 않습니다. 그냥 문제를 제시하는 형식이 좋겠습니다.

연습문제가 마지막 섹션에 폴딩되어 들어가 있습니다. 연습 문제는 폴딩이 되지 않아야 할 것 같습니다. 또는 마지막 섹션을 연습문제로 할 수도 있을 것입니다.
