### ISSUE TITLE
예제 10.4.1 설명 중 오류

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#39]
예제 10.4.1 설중 다음 부분

> 기본 트랜지션 애니메이션 효과가 일어날 때 속도가 일정하지 않고 처음에는 천천히 움직이다가 점점 
> 빨리지고 다시 느려지면서 멈춘다. 이러한 시간에 따른 움직임도 조절할 수 있는데 ease() 메소드를 이용하여 다음과 같은 움직임 함수를 선택하면 된다.
> 
> linear  : 일정한 속도로 움직임
> exp     : 지수적으로 가속
> elastic : 최종 지점을 통과하여 한번 튕긴 후 멈춤
> bounce  : 최종 지점에 부딪히고 튕기다 멈춤
> 
> 다음은 ease(“elastic”)을 이용한 예이다.
> 
> circle.transition().duration(10000).ease("elastic").attr("cx", 250);
> 
> 한 트랜지션의 시작을 지연시킬 수도 있는데 delay() 메소드를 사용한다. 다음 예는 트랜지션이 일어나기 전에 1초간 대기한 후 2초간 애니메이션이 실행된다.

다음과 같이 수정해야 합니다.

- d3.easeLinear     :  ...
- d3.easeExp         : ...
- d3.easeElastic    : ...
- d3.easeBounce   : ...

다음은 ease(d3.easeElastic)을 이용한 예이다.

circle.transition().duration(10000).ease(d3.easeElastic).attr("cx", 250);

**Comment by docuhut** [comment]
수정완료
