### ISSUE TITLE
예제의 위치가 적절하지 않음

### ISSUE THREAD

**Issue by youhj** [docuhut/webdataviz#7]
현재 오른쪽 사이드 메뉴에 위치한 예제의 위치가 적절하지 않습니다. 본문에 해당 위치로 옮기거나 오른쪽 사이드에 있더라고 그것이 있어야할 위치에 표시되어야 합니다. 10.2.1 절을 열어 보시면 부적절하다는 것을 아실 수 있습니다.

**Comment by docuhut** [comment]
본문에 내용을 다시 넣었습니다.

**Comment by youhj** [comment]
10장 만이 아니라 모든 챕터가 마찬가지입니다. 오른쪽 사이드의 커다란 예제 버튼은 현재로서는 의미가 없습니다, 모두 삭제하는 것이 좋겠습니다.
